[package]
name = "tls-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
name = "tls_parser"

[dependencies]
nom = "1.2.4"
lazy_static = "0.1.*"
# der-parser = { git = "ssh://git@git.wzdftpd.net:22/der-parser-rs.git" }

[dependencies.der-parser]
path = "/home/pollux/CODE/RUST/der-parser"

[dev_dependencies]
pcap = "0.5.7"
pnet = "0.12.0"
