[package]
name = "tls-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
build = "build.rs"

[lib]
name = "tls_parser"

[dependencies]
nom = "1.2.4"
lazy_static = "0.1.*"
phf = "0.7.16"
enum_primitive = "0.1.0"

[build-dependencies]
phf_codegen = "0.7.16"
