[package]
name = "tls-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
name = "tls_parser"

[dependencies]
nom = "1.2.4"

[dev_dependencies]
pcap = "0.5.7"
pnet = "0.12.0"
